<?php
// $Id$

/**
 * Implementation of hook_install().
 */
function world_phone_install() {
}

/**
 * Implementation of hook_update().
 *
 * update 1: delete database tables used by older version of the module.
 */
function world_phone_update_1() {
  db_query("DROP TABLE {world_phone_countries}");
  return array();
}

/**
 *  Implementation of hook_uninstall().
 */
function world_phone_uninstall() {
}
